####
# Example of what CKEditor can all bring
###

# Load default processing options
imports:
  - { resource: 'EXT:rte_ckeditor/Configuration/RTE/Processing.yaml' }
  - { resource: 'EXT:rte_ckeditor/Configuration/RTE/Editor/Base.yaml' }
  - { resource: 'EXT:rte_ckeditor/Configuration/RTE/Editor/Plugins.yaml' }

# Add configuration for the editor
# For complete documentation see https://ckeditor.com/docs/ckeditor5/latest/features/index.html
editor:
  config:
    style:
      definitions:
        # block level styles
        - { name: 'Big Title Grey H2', element: 'h2', classes: ['greyColor', 'bigTitle']}
        - { name: 'Big Title Grey H3', element: 'h3', classes: ['greyColor', 'bigTitle']}
        - { name: 'Big Title Grey H4', element: 'h4', classes: ['greyColor', 'bigTitle']}
        - { name: 'Big Title Grey H5', element: 'h5', classes: ['greyColor', 'bigTitle']}
        - { name: 'Zitat', element: 'blockquote', classes: [],  }
        - { name: 'Code-Block', element: 'code', classes: [],  }

    heading:
      options:
        - { model: 'paragraph', title: 'Paragraph' }
        - { model: 'heading2', view: 'h2', title: 'Heading 2' }
        - { model: 'heading3', view: 'h3', title: 'Heading 3' }
        - { model: 'heading4', view: 'h4', title: 'Heading 4' }
        - { model: 'heading5', view: 'h5', title: 'Heading 5' }
        - { model: 'formatted', view: 'pre', title: 'Pre-Formatted Text' }

    toolbar:
      items:
        - clipboard
        - removeFormat
        - undo
        - redo
        # grouping separator
        - '|'
        - find
        - selectAll
        - '|'
        - link
        - insertTable
        - tableColumn
        - tableRow
        - mergeTableCells
        - '|'
        - sourceEditing
        - showBlocks
        - horizontalLine
        # line break
        - '-'
        - bold
        - italic
        - underline
        - strikethrough
        - subscript
        - superscript
        - softhyphen
        - '|'
        - bulletedList
        - numberedList
        - blockQuote
        - indent
        - outdent
        - alignment
        - '|'
        - specialCharacters
        - '-'
        - style
        - heading

    alignment:
      options:
        - { name: 'left', className: 'text-start' }
        - { name: 'center', className: 'text-center' }
        - { name: 'right', className: 'text-end' }
        - { name: 'justify', className: 'text-justify' }
